# Generated by Django 4.1.3 on 2022-12-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number_dates_to_pull',
            new_name='dates_to_pull',
        ),
    ]
