# Generated by Django 4.1.3 on 2022-12-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_rename_number_dates_to_pull_profile_dates_to_pull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
