# Generated by Django 4.1.3 on 2023-02-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_rename_dates_to_pull_profile_weights_to_pull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weights_to_pull',
        ),
    ]
